import os

#PATHS
CAR_PATH = os.path.dirname(os.path.realpath(__file__))
DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')

#VEHICLE
DRIVE_LOOP_HZ = 10
FIXED_SPEED_MODE = True
FIXED_SPEED_INTERVAL = -0.5

#CAMERA
CAMERA_CAPTURE_RESOLUTION = (3280, 2464)
CAMERA_OUTPUT_RESOLUTION = (205, 154)
CAMERA_FRAMERATE = 21
CAMERA_FLIP_METHOD = 0

#STEERING
STEERING_CHANNEL = 2
STEERING_RANGE_DEGREES = 80

STEERING_MIN_PULSE = 600
STEERING_MAX_PULSE = 2400

#THROTTLE
THROTTLE_CHANNEL = 3
THROTTLE_MIN_PERCENT = 0
THROTTLE_MAX_PERCENT = 30

THROTTLE_MIN_PULSE = 1000
THROTTLE_MAX_PULSE = 2000

THROTTLE_SHIFT = 0.2
THROTTLE_STRAIGHT_INCREASE = -0.4

#LIGHTS
HEAD_LIGHT_CHANNELS = [8, 9]
REAR_LIGHT_CHANNELS = [10, 11]
BRAKE_LIGHT_CHANNELS = [12, 13]

LEFT_INDICATOR_CHANNEL = 14
RIGHT_INDICATOR_CHANNEL = 15
