import os

#PATHS
CAR_PATH = os.path.dirname(os.path.realpath(__file__))
DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')

#VEHICLE
DRIVE_LOOP_HZ = 10
FIXED_SPEED_MODE = True
FIXED_SPEED_INTERVAL = 0.05

#CAMERA
CAMERA_RESOLUTION = (160, 128)
CAMERA_FRAMERATE = 40

#STEERING
STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 1000
STEERING_RIGHT_PWM = 2000
STEERING_RANGE = 100

#THROTTLE
THROTTLE_CHANNEL = 0
THROTTLE_MIN_PERCENT = 10
THROTTLE_MAX_PERCENT = 30
