"""
CAR CONFIG

This file is read by your car application's manage.py script to change the car
performance.

EXAMPLE
-----------
import dk
cfg = dk.load_config('config.py')
print(cfg.CAMERA_RESOLUTION)
"""

import os

#PATHS
CAR_PATH = PACKAGE_PATH = os.path.dirname(os.path.realpath(__file__))

DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')
TUB_PATH = os.path.join(CAR_PATH, 'tub')

#VEHICLE
DRIVE_LOOP_HZ = 10
FIXED_SPEED_MODE = True
FIXED_SPEED_INTERVAL = 0.25

#CAMERA
CAMERA_RESOLUTION = (160, 128)
CAMERA_FRAMERATE = 40

#STEERING
STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 1000
STEERING_RIGHT_PWM = 2000
STEERING_RANGE = 100

#THROTTLE
THROTTLE_CHANNEL = 2
THROTTLE_MIN_PERCENT = 15
THROTTLE_MAX_PERCENT = 30

#TRAINING
BATCH_SIZE = 128
TRAIN_TEST_SPLIT = 0.8

#JOYSTICK
USE_JOYSTICK_AS_DEFAULT = False
JOYSTICK_MAX_THROTTLE = 1.0
JOYSTICK_STEERING_SCALE = 1.0
AUTO_RECORD_ON_THROTTLE = True

#ROPE.DONKEYCAR.COM
ROPE_TOKEN='ROPE_TOKEN'
